on:
  push:
    branches:
    - main
    paths:
    - 'ci/**'
    - '.github/workflows/ci-image.yaml'

name: Build
concurrency: release
jobs:
  ci-image:
    name: Build CI Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: ci-changes
      with:
        filters: |
          src:
          - 'ci/**'
          - '.github/workflows/*'

    - name: Build CI Image
      if: steps.ci-changes.outputs.src == 'true'
      id: build-ci-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: godot-builder
        tags: latest
        context: ci
        containerfiles: ci/Containerfile

    - name: Push CI Image
      id: push-ci-image
      if: steps.ci-changes.outputs.src == 'true'
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-ci-image.outputs.image }}
        tags: ${{ steps.build-ci-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ github.token }}


  build:
    name: Build Game
    needs: ci-image
    if: ${{ always() }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/godot-builder
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
      - ${{ github.workspace }}:/work
    steps:
    - name: Setup
      run: cp -a /root/.config /root/.local /github/home/
    - uses: actions/checkout@v3
    - name: Build + Export
      run: make ci

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/test-linux-x86_64.zip
          build/test-macos-x86_64.zip
          build/test-windows-x86_64.exe
